{% set name = "matminer" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/matminer-{{ version }}.tar.gz
  sha256: b5c338a015e1a0d4a1ca9bb229e5b07d9a8a114611b6b4b4dad73b8a6c085291
  patches:
    - setup.patch

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.5
    - numpy >=1.20.1
    - setuptools >=43.0.0
    - setuptools-scm
    - pip
  run:
    - python >=3.5
    - numpy >=1.20.1
    - requests
    - pandas >=1.5,<2.dev0
    - tqdm
    - pymongo
    - future
    - scikit-learn
    - sympy
    - monty
    - pymatgen

test:
  imports:
    - matminer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hackingmaterials/matminer
  summary: matminer is a library that contains tools for data mining in Materials Science
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jacksund
    - jan-janssen
