{% set name = "matminer" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/matminer-{{ version }}.tar.gz
  sha256: 1a37b3bb7f1e73f17e7dc2e46a67073402a37e9e506bc85ddc8229b807898901
  patches:
    - setup.patch

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 1

requirements:
  host:
    - python >=3.5
    - numpy >=1.20.1
    - setuptools >=43.0.0
    - setuptools-scm
    - pip
  run:
    - python >=3.5
    - numpy >=1.23,<2
    - requests >=2.31,<3.dev0
    - pandas >=1.5,<3
    - tqdm >=4.66,<5.dev0
    - pymongo >=4.5,<5.dev0
    - future
    - scikit-learn >=1.3,<2.dev0
    - sympy >=1.11,<2.dev0
    - monty >=2023
    - pymatgen >=2023

test:
  imports:
    - matminer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hackingmaterials/matminer
  summary: matminer is a library that contains tools for data mining in Materials Science
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jacksund
    - jan-janssen
