{% set name = "matminer" %}
{% set version = "0.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2f2b1258e13973c9bf5db187d666083ee9eddceed6234b980f507d3d326ae182

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - pip
    - numpy >=1.18.3
    - requests >=2.20.0
    - pymatgen >=2019.10.2
    - pandas >=0.23.4
    - tqdm >=4.23.1
    - pymongo >=3.11.2
    - pint >=0.8.1
    - six >=1.16.0
    - plotly >=3.2.1
    - future >=0.16.0
    - sympy >=1.6
    - scikit-learn >=0.21.3
    - monty >=3.0.1

test:
  imports:
    - matminer
  commands:
    - pip check

about:
  home: https://hackingmaterials.lbl.gov/matminer/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: data mining for Materials Science

  description: |
    matminer is a library for performing data mining in the field of 
    materials science.
  doc_url: https://hackingmaterials.lbl.gov/matminer/
  dev_url: https://github.com/hackingmaterials/matminer

extra:
  recipe-maintainers:
    - jan-janssen
