{% set name = "matminer" %}
{% set version = "0.10.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/matminer-{{ version }}.tar.gz
  sha256: 6f52c821d3323f586a8f6f23e7eca296cb80ce5aab9754fc0c788c27ed73b5fa

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - numpy >=1.20.1
    - setuptools >=43.0.0
    - setuptools-scm
    - pip
  run:
    - scipy >=1.17.0
    - python >={{ python_min }}
    - numpy >=1.23
    - requests >=2.31,<3.dev0
    - pandas >=1.5,<3
    - tqdm >=4.66,<5.dev0
    - pymongo >=4.5,<5.dev0
    - future
    - scikit-learn >=1.3,<2.dev0
    - sympy >=1.11,<2.dev0
    - monty >=2023
    - pymatgen >=2023

test:
  imports:
    - matminer
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hackingmaterials/matminer
  summary: matminer is a library that contains tools for data mining in Materials Science
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jacksund
    - jan-janssen
