{% set name = "matminer" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2e4f0db79cc118d171a93aafb3a6edcff3f863d1f73cbfcdedd6f10bfdb2c34f 

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - pip
    - numpy >=1.17.2
    - requests >=2.20.0
    - pymatgen >=2019.10.2
    - pandas >=0.23.4
    - tqdm >=4.23.1
    - pymongo >=3.6.1
    - pint =0.10
    - six >=1.11.0
    - plotly >=3.2.1
    - future >=0.16.0
    - sympy >=1.1.1
    - scikit-learn >=0.21.3
    - monty >=3.0.1
    - ujson >=1.35
    - jmespath >=0.9.3
    - httplib2 >=0.10.3
    - ase >=3.14.1
    - dscribe >=0.2.9
    - mdf_forge >=0.6.1
    - aflow >=0.0.9
    - citrination-client >=4.0.1

test:
  imports:
    - matminer
  commands:
    - pip check

about:
  home: https://hackingmaterials.lbl.gov/matminer/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'data mining for Materials Science'

  description: |
    matminer is a library for performing data mining in the field of 
    materials science.
  doc_url: https://hackingmaterials.lbl.gov/matminer/
  dev_url: https://github.com/hackingmaterials/matminer

extra:
  recipe-maintainers:
    - jan-janssen
